function autofitautotest(method)
    if nargin == 0
        method = 'bowties';
    end
    molnames = {    ...
                    '1-pentanol',...
                    'a_isomethyl_ionone',...
                    'annso',...
                    'bacdanol',...
                    'benzyl_acetate',...
                    'benzyl_alcohol',...
                    'benzyl_benzoate',...
                    'butanol_1d',...
                    'cedramber',...
                    'cinnamyl_alcohol',...
                    'cyclohexanol',...
                    'dioxolane',...
                    'ethanol',...
                    'ethylbutyrate',...
                    'ethylphenol',...
                    'eucalyptus',...
                    'fenugreek',...
                    'ginger',...
                    'guaiacol',...
                    'heptaldehyde',...
                    'hexanal',...
                    'linalool_oxide',...
                    'phellandrene',...
                    'phellandrene2',...
                    'propanediolWide',...
...%                     'pulegone',...
                    'Rosemary',...
                    'sage',...
                    'Teatree oil',...
                    };
%     molnames = {    'alpha_pinene',...
%                     'alpha_terpineol',...
%                     'angelica',...
%                     'benzaldehyde',...
%                     'BenzOD',...
%                     'betapinene',...
%                     'cinnamaldehyde',...
%                     'ethylguiacol',...
%                     'Lemon Oil',...
%                     'Orange Extract',...
%                     'myrtenal',...
%                     'myrtenol',...
%                     'menthone',...
%                     'm_anisaldehyde',...
%                     'nopinone',...
%                     'oregano',...
%                     'anisaldehyde',...
%                     'florol',...
%                     'sabinene'...
%                     };
    nummolecules = length(molnames);
    for i = 1:nummolecules
        fprintf('Testing %s:\n', molnames{i});
        filename = completeFilename(molnames{i});
        autofit(filename,method);
    end
end